---

- hosts: all
  become: true
  vars_files:
    - ./sudo_password.yml
  pre_tasks:
  - name: update repository index and packages
    tags: always  
    package:
      update_cache: yes
      upgrade: dist
      
- hosts: raspberry
  become: true
  vars_files:
    - ./sudo_password.yml  
  roles:
    - {role: vandycknick.security.ssh}