---

- hosts: all
  become: true
  vars_files:
    - ./sudo_password.yml
  pre_tasks:
  - name: update Ubuntu repository index and packages
    tags: always  
    package:
      update_cache: yes
      upgrade: dist
    when: ansible_facts['distribution'] == "Ubuntu"
  - name: update Raspbian repository index and packages
    tags: always  
    package:
      update_cache: yes
      upgrade: dist
    when: ansible_facts['distribution'] == "Debian"
      
- hosts: all
  become: true
  tags: ssh
  vars_files:
    - ./sudo_password.yml  
  roles:
    - {role: vandycknick.security.ssh}

- hosts: raspberry
  become: true
  vars_files:
    - ./sudo_password.yml  
    - vars
  roles:
    - { role: geerlingguy.raspberry-pi }

- hosts: pihole
  become: true
  vars_files:
    - ./sudo_password.yml
    - vars
  roles:
    - role: r_pufky.pihole
      pihole_ipv4_address: '192.168.178.2/24'
      pihole_pihole_dns_1: '1.1.1.1'
      pihole_dhcp_start: '192.168.178.100'
      pihole_dhcp_end: '192.168.178.250'
      pihole_dhcp_router: '192.168.178.1'
      pihole_pihole_interface: 'wlan0'
      pihole_webpassword: '{{pihole_password}}'
      pihole_dhcp_active: 'true'
      pihole_pihole_domain: 'local'

