---
dependencies: []

galaxy_info:
  role_name: raspberry-pi
  author: geerlingguy
  description: Configures a Raspberry Pi.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - system
    - raspberry
    - pi
    - raspbian