- name: Init a new swarm with default parameters
  become: true
  community.docker.docker_swarm:
    state: present
    name: default
  register: swarm_facts

- name: set output
  set_fact:
    token: "{{ swarm_facts.swarm_facts.JoinTokens.Worker }}"